name: 'Purge css action'
description: 'Remove unused selectors from css files'
inputs: 
  test_var:
    description: 'A test variable'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
